services:
  backend:
    build:
      context: ./backend
      args:
        API_URL: ${API_URL}
        REDIRECT_URI: ${REDIRECT_URI}
        LOGOUT_URI: ${LOGOUT_URI}
    ports:
      - "8080:8080"
    environment:
      - API_URL=${API_URL}
      - REDIRECT_URI=${REDIRECT_URI}
      - LOGOUT_URI=${LOGOUT_URI}

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend